### ISSUE TITLE
mkdocs update?

### ISSUE THREAD

**Issue by juju4** [PagerDuty/incident-response-docs#106]
Any plan to upgrade to latest mkdocs? (1.0.4 from https://github.com/mkdocs/mkdocs)

update to 0.17.5 creates issue
But this version or above is required for python 3.7 else 
`RuntimeError: generator raised StopIteration`
https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app
https://www.python.org/dev/peps/pep-0479/

**Comment by richadams** [comment]
Hi @juju4,

Yes, we're planning on upgrading this repo so that it'll work with the latest version of MkDocs. Right now the main thing preventing the upgrade is our choice of customized theme. If you have a fork of the repository, you should be able to change to a different theme and use the latest MkDocs without much issue.

I can't offer a timeframe for when we'll publish our changes, but it's definitely on my radar and I'll leave this issue open until the work is complete.

Thanks,
Rich

**Comment by richadams** [comment]
https://github.com/PagerDuty/incident-response-docs/pull/120 should solve this. We're now on the latest Python and MkDocs version, yay! 🎉
