### ISSUE TITLE
Ack clarification

### ISSUE THREAD

**Issue by fromonesrc** [PagerDuty/incident-response-docs#21]
I'm trying to make sense of these two statements but they seem to conflict. Maybe I am misunderstanding what I'm reading.

> No expectation to be the first to acknowledge all of the alerts during the on-call period. Commute (and other necessary distractions) are facts of life, and sometimes it is not possible to receive or act on an alert before it escalates. That's what we have the backup on-call and schedule for.

> Don't acknowledge an incident out from under someone else. If you didn't get paged for the incident, then you shouldn't be acknowledging it. Add a comment with your notes instead. 

I _think_ what this is trying to convey is "it's ok to help your team mates if they can't ack the alert right away but don't make a habit out of it" but I'm unsure. Would you mind clarifying? Thanks!

**Comment by richadams** [comment]
Sure! I'll try to clarify with some examples. Let me know if this all makes sense and I'll work on including the clarifications into the docs themselves.

----

The first paragraph is referring to people who are oncall for your service, whether as primary or secondary. The second paragraph is referring to someone who is not currently oncall trying to take ownership of an incident before the actually responder has had chance to look.

It essentially comes down to: _"You shouldn't acknowledge an incident unless you specifically got paged for it"_

Let me give two examples to make it clearer,

---
#### Example 1

    1. User A gets paged for an incident, but is unable to respond due to commute.
    2. Incident automatically escalates to User B (who gets paged) after x minutes.
    3. User B acknowledges incident and starts response.

This example shows the intent of the first paragraph you referenced. Two users are oncall, one as primary (A), one as backup/secondary (B). User A is unable to respond due to commute, but the incident automatically escalates to User B after a certain amount of time. User B can then acknowledge and respond normally.

---
#### Example 2

    1. User A gets paged for an incident.
    2. User C see's incident in the dashboard and acknowledges.

In this case, User C has gone against our oncall etiquette. User C was not paged for this incident, yet acknowledged it out from under User A. Now User A will receive a page, and then will wonder why they no longer see the incident assigned to them, adding confusion and slowing down the response. 

In our experience, this typically happens when User C is trying to be helpful, and not because they're trying to be disruptive ("Oh, I see they got paged for this. I can fix that right now, let me be nice and acknowledge it for them!"). While this is certainly a nice gesture, we've found that this behaviour ends up adding too much confusion to the user who is actually oncall (A), and so we actively discourage it in our documentation.

**Comment by fromonesrc** [comment]
This clarifies greatly. I didn't realize you were talking about backup on-call acking versus general team acking. Thanks for the detailed reply! ❤️
